#!/usr/bin/env python 3.6
# -*- coding: utf-8 -*-
import csv
import os
import json
from pathlib import Path
with open('departements-france.csv', mode='r') as csvfile:
    spamreader = csv.DictReader(csvfile)
    for row in spamreader:
        if not os.path.exists(row["nom_region"]):
            os.makedirs(row["nom_region"])
        for element in os.listdir('.'):
            if element == row["nom_region"]:
                if not os.path.exists(row["nom_region"] + '/' +row["nom_departement"]):
                    os.chdir(element)
                    os.makedirs(row["nom_departement"])
                    os.chdir('..')

with open('liste-des-immeubles-proteges-au-titre-des-monuments-historiques.json', encoding='utf-8') as jsonfile:
    monument = json.load(jsonfile)
    for row in monument:
        try:
            if 'dpt_lettre'in row["fields"]:
                fichier = open('./' + row["fields"]["reg"] + "/" + row["fields"]["dpt_lettre"] + "/" + row["fields"]["tico"].replace("\'", " ") + ".txt", 'wt')
                fichier.writelines(row['fields']['reg'])
                fichier.close()
        except Exception:
            pass
