#!/usr/bin/env python 3.6
# -*- coding: utf-8 -*-
import csv
import os
import json
import re
from pathlib import Path
#Création de l'arborescence des fichiers Regions avec leurs Departements associés
with open('departements-france.csv', mode='r') as csvfile:
    spamreader = csv.DictReader(csvfile)
    for row in spamreader:
        if not os.path.exists(row["nom_region"]):
            os.makedirs(row["nom_region"])
        for element in os.listdir('.'):
            if element == row["nom_region"]:
                if not os.path.exists(row["nom_region"] + '/' +row["nom_departement"]):
                    os.chdir(element)
                    os.makedirs(row["nom_departement"])
                    os.chdir('..')
#Parcours du fichier JSon pour en extraire certaines données (re.search) et les associer dans les départements d'origine par la création d'un fichier txt
with open('liste-des-immeubles-proteges-au-titre-des-monuments-historiques.json', encoding='utf-8') as jsonfile:
    monument = json.load(jsonfile)
    for row in monument:
        tico = row["fields"]["tico"].replace("\'", " ")
        def roi(strTico):
            match = re.search('Hugues|Robert|Henri|Philippe|Louis|Jean|Charles', strTico)
            if match:
                result = True
            else:
                result = False
            return result

        try:
            if 'dpt_lettre' in row["fields"] and roi(tico) is True:
                fichier = open('./' + row["fields"]["reg"] + "/" + row["fields"]["dpt_lettre"] + "/" + tico + ".yml", 'wt')
                fichier.writelines("Nom : " + tico + "\n")
                fichier.writelines("Description : " + row['fields']['stat'].replace("\'", " ") + "\n")
                fichier.writelines("Commune : " + row['fields']['commune'] + "\n")
                fichier.writelines("Localisation :" + "\n")
                fichier.writelines("Latitude :" + row["fields"]["coordonnees_ban"][0])
                fichier.writelines("Longitude :" + row["fields"]["coordonnees_ban"][1])
                fichier.close()
        except Exception:
            pass
